defaults: &defaults
  working_directory: ~/remix-etherscan
  docker:
    - image: circleci/node:12.16

aliases:
  - &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
        - yarn-packages-{{ .Branch }}-

version: 2.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install Dependencies
          command: |
            echo 'Installing dependencies'
            yarn install
      - save_cache: 
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  
  tslint-and-format: 
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: TSLint
          command: yarn tslint
      - run:
          name: Check formatting (Prettier)
          command: yarn check-formatting
  
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Run unit tests with JUnit as reporter
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  audit: 
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Audit
          command: yarn audit

  build: 
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Build
          command: yarn build

  publish: 
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Publish
          command: yarn publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - tslint-and-format:
          requires:
            - setup
      - unit-tests:
          requires:
            - setup
      - audit:
          requires:
            - setup
      - bundle:
          requires:
            - tslint-and-format
            - unit-tests
            - audit
      - publish:
          context: SolidStudio
          requires:
            - bundle
          filters:
            branches:
              only: master